
package reservation.passenger.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "passengerProfileType", targetNamespace = "http://www.example.org/passengerProfile/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PassengerProfileType {


    /**
     * 
     * @param passengerProfileCreateRequest
     * @return
     *     returns reservation.passenger.service.PassengerProfileCreateResponseType
     */
    @WebMethod(action = "http://www.example.org/passengerProfile/createPassengerProfile")
    @WebResult(name = "passengerProfileCreateResponse", targetNamespace = "")
    @RequestWrapper(localName = "createPassengerProfile", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.CreatePassengerProfile")
    @ResponseWrapper(localName = "createPassengerProfileResponse", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.CreatePassengerProfileResponse")
    public PassengerProfileCreateResponseType createPassengerProfile(
        @WebParam(name = "passengerProfileCreateRequest", targetNamespace = "")
        PassengerProfileCreateRequestType passengerProfileCreateRequest);

    /**
     * 
     * @param passengerProfileGetRequest
     * @return
     *     returns reservation.passenger.service.PassengerProfileGetResponseType
     */
    @WebMethod(action = "http://www.example.org/passengerProfile/getPassengerProfile")
    @WebResult(name = "passengerProfileGetResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPassengerProfile", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.GetPassengerProfile")
    @ResponseWrapper(localName = "getPassengerProfileResponse", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.GetPassengerProfileResponse")
    public PassengerProfileGetResponseType getPassengerProfile(
        @WebParam(name = "passengerProfileGetRequest", targetNamespace = "")
        PassengerProfileGetRequestType passengerProfileGetRequest);

    /**
     * 
     * @param passengerProfileUpdateRequest
     * @return
     *     returns reservation.passenger.service.PassengerProfileUpdateResponseType
     */
    @WebMethod(action = "http://www.example.org/passengerProfile/updatePassengerProfile")
    @WebResult(name = "passengerProfileUpdateResponse", targetNamespace = "")
    @RequestWrapper(localName = "updatePassengerProfile", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.UpdatePassengerProfile")
    @ResponseWrapper(localName = "updatePassengerProfileResponse", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.UpdatePassengerProfileResponse")
    public PassengerProfileUpdateResponseType updatePassengerProfile(
        @WebParam(name = "passengerProfileUpdateRequest", targetNamespace = "")
        PassengerProfileUpdateRequestType passengerProfileUpdateRequest);

    /**
     * 
     * @param passengerProfileDeleteRequest
     * @return
     *     returns reservation.passenger.service.PassengerProfileDeleteResponseType
     */
    @WebMethod(action = "http://www.example.org/passengerProfile/deletePassengerProfile")
    @WebResult(name = "passengerProfileDeleteResponse", targetNamespace = "")
    @RequestWrapper(localName = "deletePassengerProfile", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.DeletePassengerProfile")
    @ResponseWrapper(localName = "deletePassengerProfileResponse", targetNamespace = "http://www.example.org/passengerProfile/", className = "reservation.passenger.service.DeletePassengerProfileResponse")
    public PassengerProfileDeleteResponseType deletePassengerProfile(
        @WebParam(name = "passengerProfileDeleteRequest", targetNamespace = "")
        PassengerProfileDeleteRequestType passengerProfileDeleteRequest);

}
