
package reservation.passenger.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "passengerProfile", targetNamespace = "http://www.example.org/passengerProfile/", wsdlLocation = "file:/C:/Users/Din/RESTworkspace/AirlineReservation/AirlineSOAPServices/src/main/resources/passengerProfile.wsdl")
public class PassengerProfile
    extends Service
{

    private final static URL PASSENGERPROFILE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(reservation.passenger.service.PassengerProfile.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = reservation.passenger.service.PassengerProfile.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Din/RESTworkspace/AirlineReservation/AirlineSOAPServices/src/main/resources/passengerProfile.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Din/RESTworkspace/AirlineReservation/AirlineSOAPServices/src/main/resources/passengerProfile.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PASSENGERPROFILE_WSDL_LOCATION = url;
    }

    public PassengerProfile(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PassengerProfile() {
        super(PASSENGERPROFILE_WSDL_LOCATION, new QName("http://www.example.org/passengerProfile/", "passengerProfile"));
    }

    /**
     * 
     * @return
     *     returns PassengerProfileType
     */
    @WebEndpoint(name = "passengerProfile")
    public PassengerProfileType getPassengerProfile() {
        return super.getPort(new QName("http://www.example.org/passengerProfile/", "passengerProfile"), PassengerProfileType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassengerProfileType
     */
    @WebEndpoint(name = "passengerProfile")
    public PassengerProfileType getPassengerProfile(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/passengerProfile/", "passengerProfile"), PassengerProfileType.class, features);
    }

}
